name: appsguide
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  http: ^0.13.4
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0
  page_transition: ^2.0.5
  accordion: ^2.3.0
  webview_flutter: ^3.0.4
  google_maps_flutter: ^2.1.8
  flutter_google_street_view: ^2.2.7
  google_maps_flutter_web: ^0.4.0
  video_player: ^2.4.4
  font_awesome_flutter: ^8.10.0
  community_material_icon: ^5.4.55


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/video/
  
  fonts: 
    - family: My_icons
      fonts: 
        - asset: assets/My_icons.ttf
