/// Flutter icons My_icons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_icons
///      fonts:
///       - asset: fonts/My_icons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class My_icons {
  My_icons._();

  static const _kFontFam = 'My_icons';
  static const String? _kFontPkg = null;

  static const IconData key = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xf0f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
